// Socket Actions
export const SOCKET_LOADING = 'SOCKET_LOADING';
export const SOCKET_SUCCESS = 'SOCKET_SUCCESS';
export const SOCKET_FAIL = 'SOCKET_FAIL';
export const CONNECTION_ACK = 'CONNECTION_ACK';
export const CONNECTION_DENY = 'CONNECTION_DENY';

// Room Actions
export const ROOM_LOADING = 'ROOM_LOADING';
export const ROOM_SUCCESS = 'ROOM_SUCCESS';
export const ROOM_FAIL = 'ROOM_FAIL';

// Team Actions
export const TEAM_LOADING = 'TEAM_LOADING';
export const TEAM_SUCCESS = 'TEAM_SUCCESS';
export const TEAM_FAIL = 'TEAM_FAIL';

// Chat Actions
export const CHANGED_CHAT_TYPE = 'CHANGED_CHAT_TYPE';
export const CHAT_EVERYONE_SUCCESS = 'CHAT_EVERYONE_SUCCESS';
export const CHAT_TEAM_SUCCESS = 'CHAT_TEAM_SUCCESS';
export const CHAT_FAIL = 'CHAT_FAIL';

// Veto Actions
export const VETO_START_ADMIN = 'VETO_START_ADMIN';
export const VETO_GET_ALL_USERS = 'VETO_GET_ALL_USERS';
export const VETO_START_SERVER = 'VETO_START_SERVER';
export const VETO_STOP_SERVER = 'VETO_STOP_SERVER';
export const VETO_USER_VOTED = 'VETO_USER_VOTED';
export const VETO_FAIL = 'VETO_FAIL';
export const VETO_QUESTIONS_LOADING = 'VETO_QUESTIONS_LOADING';
export const VETO_QUESTIONS_SUCCESS = 'VETO_QUESTIONS_SUCCESS';
export const VETO_QUESTIONS_FAIL = 'VETO_QUESTIONS_FAIL';
export const VETO_ADD_VOTE_QUESTION = 'VETO_ADD_VOTE_QUESTION';
export const VETO_REMOVE_VOTE_QUESTION = 'VETO_REMOVE_VOTE_QUESTION';
export const VETO_USER_VOTED_STATUS = 'VETO_USER_VOTED_STATUS';

// Arena Actions
export const ARENA_QUESTIONS_LOADING = 'ARENA_QUESTIONS_LOADING';
export const ARENA_QUESTIONS_SUCCESS = 'ARENA_QUESTIONS_SUCCESS';
export const ARENA_QUESTIONS_FAIL = 'ARENA_QUESTIONS_FAIL';
export const ARENA_COMPETITION_STOPPED = 'ARENA_COMPETITION_STOPPED';
export const ARENA_COMPETITION_STARTED = 'ARENA_COMPETITION_STARTED';

// Code Submissions
export const ARENA_CODE_SUBMIT_LOADING = 'ARENA_CODE_SUBMIT_LOADING';
export const ARENA_CODE_SUBMIT_SUCCESS = 'ARENA_CODE_SUBMIT_SUCCESS';
export const ARENA_CODE_SUBMIT_FAIL = 'ARENA_CODE_SUBMIT_FAIL';

export const ARENA_ROOM_CODE_SUBMIT_STATUS = 'ARENA_ROOM_CODE_SUBMIT_STATUS';

// Reset action
export const ACTION_RESET = 'ACTION_RESET';
export const ARENA_DATA_RESET = 'ARENA_DATA_RESET';
