// PreCheck actions
export const PRECHECK_LOADING = 'PRECHECK_LOADING';
export const PRECHECK_SUCCESS = 'PRECHECK_SUCCESS';
export const PRECHECK_FAIL = 'PRECHECK_FAIL';

// Login Actions
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

// Signup Actions
export const SIGNUP_LOADING = 'SIGNUP_LOADING';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

// Delete Account Actions
export const DELETE_ACCOUNT_LOADING = 'DELETE_ACCOUNT_LOADING';
export const DELETE_ACCOUNT_SUCCESS = 'DELETE_ACCOUNT_SUCCESS';
export const DELETE_ACCOUNT_FAIL = 'DELETE_ACCOUNT_FAIL';

// Update Account Actions
export const UPDATE_ACCOUNT_LOADING = 'UPDATE_ACCOUNT_LOADING';
export const UPDATE_ACCOUNT_SUCCESS = 'UPDATE_ACCOUNT_SUCCESS';
export const UPDATE_ACCOUNT_FAIL = 'UPDATE_ACCOUNT_FAIL';

// Logout user
export const LOGOUT_LOADING = 'LOGOUT_LOADING';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

// Username check
export const USERNAME_CHECK_LOADING = 'USERNAME_CHECK_LOADING';
export const USERNAME_CHECK_SUCCESS = 'USERNAME_CHECK_SUCCESS';
export const USERNAME_CHECK_FAIL = 'USERNAME_CHECK_FAIL';

// Socket Actions
export const SOCKET_LOADING = 'SOCKET_LOADING';
export const SOCKET_SUCCESS = 'SOCKET_SUCCESS';
export const SOCKET_FAIL = 'SOCKET_FAIL';
export const CONNECTION_ACK = 'CONNECTION_ACK';
export const CONNECTION_DENY = 'CONNECTION_DENY';

// Room Actions
export const ROOM_LOADING = 'ROOM_LOADING';
export const ROOM_SUCCESS = 'ROOM_SUCCESS';
export const ROOM_FAIL = 'ROOM_FAIL';

// Team Actions
export const TEAM_LOADING = 'TEAM_LOADING';
export const TEAM_SUCCESS = 'TEAM_SUCCESS';
export const TEAM_FAIL = 'TEAM_FAIL';

// Chat Actions
export const CHAT_SUCCESS = 'CHAT_SUCCESS';
export const CHAT_FAIL = 'CHAT_FAIL';

// Veto Actions
export const VETO_START_ADMIN = 'VETO_START_ADMIN';
export const VETO_START_SERVER = 'VETO_START_SERVER';
export const VETO_STOP_SERVER = 'VETO_STOP_SERVER';
export const VETO_USER_VOTED = 'VETO_USER_VOTED';
export const VETO_FAIL = 'VETO_FAIL';
export const VETO_QUESTIONS_LOADING = 'VETO_QUESTIONS_LOADING';
export const VETO_QUESTIONS_SUCCESS = 'VETO_QUESTIONS_SUCCESS';
export const VETO_QUESTIONS_FAIL = 'VETO_QUESTIONS_FAIL';
export const VETO_ADD_VOTE_QUESTION = 'VETO_ADD_VOTE_QUESTION';
export const VETO_REMOVE_VOTE_QUESTION = 'VETO_REMOVE_VOTE_QUESTION';

// Arena Actions
export const ARENA_QUESTIONS_LOADING = 'ARENA_QUESTIONS_LOADING';
export const ARENA_QUESTIONS_SUCCESS = 'ARENA_QUESTIONS_SUCCESS';
export const ARENA_QUESTIONS_FAIL = 'ARENA_QUESTIONS_FAIL';

// Code Submissions
export const CODE_SUBMIT_LOADING = 'CODE_SUBMIT_LOADING';
export const CODE_SUBMIT_SUCCESS = 'CODE_SUBMIT_SUCCESS';
export const CODE_SUBMIT_FAIL = 'CODE_SUBMIT_FAIL';

// Reset action
export const ACTION_RESET = 'ACTION_RESET';
