import React from 'react';
import './Chat.css';

function Chat() {
  return (
    <div className='chat-body'>
      <div className='chat-header'>CHAT</div>
      <div className='chat-container'>
        {' '}
        JOEL OP JOEL OP JOEL OP JOEL OP JOEL OP JOEL OP JOEL OP JOEL OP JOEL OP
        JOEL OP JOEL OP JOEL OP JOEL OP JOEL OP JOEL OP JOEL OP JOEL OP JOEL OP
        JOEL OP JOEL OP JOEL OP JOEL OP JOEL OP JOEL OP JOEL OP JOEL OP JOEL OP
        JOEL OP JOEL OP JOEL OP JOEL OP JOEL OP JOEL OP JOEL OP JOEL OP JOEL OP
        JOEL OP JOEL OP JOEL OP JOEL OP JOEL OP JOEL OP JOEL OP JOEL OP JOEL OP
        JOEL OP JOEL OP JOEL OP JOEL OP JOEL OP JOEL OP JOEL OP JOEL OP JOEL OP
        JOEL OP JOEL OP JOEL OP JOEL OP JOEL OP JOEL OP JOEL OP JOEL OP JOEL OP
        JOEL OP JOEL OP JOEL OP JOEL OP JOEL OP JOEL OP JOEL OP JOEL OP JOEL OP
        JOEL OP JOEL OP JOEL OP JOEL OP JOEL OP JOEL OP JOEL OP JOEL OP JOEL OP
        JOEL OP JOEL OP JOEL OP JOEL OP JOEL OP JOEL OP JOEL OP JOEL OP JOEL OP
        JOEL OP JOEL OP JOEL OP JOEL OP JOEL OP JOEL OP JOEL OP JOEL OP JOEL OP
        JOEL OP JOEL OP JOEL OP JOEL OP JOEL OP JOEL OP JOEL OP
      </div>
    </div>
  );
}

export default Chat;
