# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
        mongodb-version: [4.2]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Start MongoDB v${{ matrix.mongodb-version }}
      uses: supercharge/mongodb-github-action@1.2.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
    - run: npm ci
    - run: npm install
    - run: npm run prettier:check --if-present
    - run: npm run lint --if-present
    - run: npm test --if-present
      env:
        TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        ACCESS_SECRET_KEY: ${{ secrets.ACCESS_SECRET_KEY }}
        ACCESS_SECRET_TIME: ${{ secrets.ACCESS_SECRET_TIME }}
        REFRESH_SECRET_KEY: ${{ secrets.REFRESH_SECRET_KEY }}
        REFRESH_SECRET_TIME: ${{ secrets.REFRESH_SECRET_TIME }}
        EMAILVERIFICATION_SECRET_KEY: ${{ secrets.EMAILVERIFICATION_SECRET_KEY }}
        EMAILVERIFICATION_SECRET_TIME: ${{ secrets.EMAILVERIFICATION_SECRET_TIME }}
        FACEBOOK_APP_ID: ${{ secrets.FACEBOOK_APP_ID }}
        FACEBOOK_APP_SECRET: ${{ secrets.FACEBOOK_APP_SECRET }}
        FACEBOOK_APP_URL: ${{ secrets.FACEBOOK_APP_URL }}
        MAIL: ${{ secrets.MAIL }}
        MAILPASS: ${{ secrets.MAILPASS }}
    - run: TOKEN=${{ secrets.CODECOV_TOKEN }} npm run test:jest:codecov --if-present
    - run: npm run test-coverage --if-present
    - run: PORT=${{ secrets.CODECOV_TOKEN }} npm run codecov --if-present
    env:
        CI: true
